# Generated by Django 4.1.1 on 2022-10-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Highly_recommended',
            new_name='highly_recommended',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=70),
        ),
    ]
