# Generated by Django 4.1.1 on 2022-10-12 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_description_post_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thingstodo', models.CharField(max_length=150)),
                ('placestovisit', models.CharField(max_length=150)),
                ('userrating', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='main_app.post')),
            ],
        ),
    ]
